server:
  port: 3000
  jwt:
    secret: "changemeplease"

db:
  user: "tikkin"
  database: "tikkin"
  password: "tikkin"
  port: 5432
  connections: 10
  #host: "postgres"
  host: localhost

admin:
  email: user@example.com

links:
  length: 6

