server:
  port: 3000
  jwt:
    secret: "changemeplease"

site:
  name: "Tikk.in"
  url: https://tikk.in

email:
  enabled: true
  smtp:
    host:
    port: 587
    username:
    from: "noreply@tikk.in"

db:
  user: "tikkin"
  database: "tikkin"
  password: "tikkin"
  port: 5432
  connections: 10
  #host: "postgres"
  host: localhost

admin:
  email: user@example.com

links:
  length: 6

