// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"time"
)

type Link struct {
	ID          int64
	UserID      int64
	Slug        string
	Description *string
	Banned      bool
	ExpireAt    *time.Time
	TargetUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID                int64
	Email             string
	Password          string
	Verified          bool
	VerificationToken *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Visit struct {
	ID          string
	LinkID      int64
	CreatedAt   time.Time
	UserAgent   *string
	Referrer    *string
	CountryCode *string
}
